### ISSUE TITLE
Do you have any questions？？[宁有什么问题？？！！]

### ISSUE THREAD

**Issue by Timolop233** [TextWar/TextWar-Web#2]
If you have any questions about the website, you can ask them here. We will give you a reply or fix the bug when we see it！！！
[有问题给我憋着！！！]

**Comment by MagicLu550** [comment]
Oh,Do not Tree New Bee,FUNNY MUD PEE (Dog Head to save life)

**Comment by MagicLu550** [comment]
PLEASE MERGE OK?MY LITTLE BOY?
HETUI

**Comment by Timolop233** [comment]
2333333333333333

**Comment by Timolop233** [comment]
Boss, I'm wrong. I'll sweep the floor now

**Comment by MagicLu550** [comment]
OK,But i hope that the pr is merged

**Comment by MagicLu550** [comment]
NOT JUST SAY IT (HUA JI)
